# Generated by Django 2.2.4 on 2019-08-29 00:33

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name of User')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name of User')),
                ('country_code', django_countries.fields.CountryField(max_length=2, verbose_name='Country code of User')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number of User')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender of User')),
                ('birth_date', models.DateField(verbose_name='Birth date of User')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Image of User')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email of User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
