# Generated by Django 2.2.4 on 2019-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'blank'}, max_length=50, verbose_name='First name of User'),
        ),
    ]
